export {updateName} from './reduxActions'
export {updateEmail} from './reduxActions'
export {updateAddress} from './reduxActions'
export {updatePhoneNumber} from './reduxActions'
export {addEducation} from './reduxActions'
export {updateEducation} from './reduxActions'
export {removeEducation} from './reduxActions'
export {updateProject} from './reduxActions'
export {addProject} from './reduxActions'
export {removeProject} from './reduxActions'
export {updateExperience} from './reduxActions'
export {addExperience} from './reduxActions'
export {removeExperience} from './reduxActions'
export {addSkills} from './reduxActions'

